---
name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Have an idea? We'd love to hear it.
        Here're a few questions that might help you explain.
        Answer as many or as few as you'd like.

  - type: textarea
    attributes:
      label: Is your feature request related to a problem?

  - type: textarea
    attributes:
      label: Describe the solution you'd like.

  - type: textarea
    attributes:
      label: Describe alternatives you've considered.

  - type: textarea
    attributes:
      label: Any other context or screenshots about the feature request?

  - type: checkboxes
    attributes:
      label: "​"
      options:
        - label: I want to work on this feature
