name: Build and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CHROME_PUBLIC_KEY: ${{ vars.CHROME_PUBLIC_KEY }}
  FIREFOX_EXTENSION_ID: ${{ vars.FIREFOX_EXTENSION_ID }}

jobs:
  artifact:
    runs-on: ubuntu-latest
    needs: [typecheck, format, lint, test]
    steps:
      - &checkout_step
        name: Checkout
        uses: actions/checkout@v6

      - &install_step
        name: Install
        uses: ./.github/actions/install

      - &build_step
        name: Build
        uses: ./.github/actions/build

      - name: Upload Chrome Extension
        uses: actions/upload-artifact@v7
        with:
          name: chrome-extension
          path: '.output/chrome-mv3'
          if-no-files-found: error

      - name: Upload Firefox Extension
        uses: actions/upload-artifact@v7
        with:
          name: firefox-extension
          path: '.output/firefox-mv3'
          if-no-files-found: error

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - *checkout_step
      - *install_step
      - name: Type check
        run: npm run typecheck

  format:
    runs-on: ubuntu-latest
    steps:
      - *checkout_step
      - *install_step

      - name: Prettier
        run: npm run format

  lint:
    runs-on: ubuntu-latest
    steps:
      - *checkout_step
      - *install_step
      - *build_step

      - name: ESLint
        run: npm run lint .github/workflows

      - name: Run AMO linter
        run: npx addons-linter .output/firefox-mv3

      # Linter for Chrome?

  test:
    runs-on: ubuntu-latest
    steps:
      - *checkout_step
      - *install_step
      - *build_step

      - name: Playwright Test
        uses: ./.github/actions/test
