name: Build and Test

on:
  pull_request:
    branches: [main]
    paths-ignore: ['**/*.md']
  push:
    branches: [main]
    paths-ignore: ['**/*.md']

env:
  CHROME_PUBLIC_KEY: ${{ vars.CHROME_PUBLIC_KEY }}
  FIREFOX_EXTENSION_ID: ${{ vars.FIREFOX_EXTENSION_ID }}

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - &checkout_step
        name: Checkout
        uses: actions/checkout@v6

      - &setup_step
        name: Setup
        uses: ./.github/actions/setup

      - name: Type check
        run: npm run typecheck

  format:
    runs-on: ubuntu-latest
    steps:
      - *checkout_step
      - *setup_step

      - name: Prettier
        run: npm run format

  lint:
    runs-on: ubuntu-latest
    steps:
      - *checkout_step
      - *setup_step

      - name: ESLint
        run: npm run lint .github/workflows

      - name: Run AMO linter
        run: npx addons-linter .output/firefox-mv3

      # Linter for Chrome?

  test:
    runs-on: ubuntu-latest
    steps:
      - *checkout_step
      - *setup_step

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: xvfb-run npm test

  build:
    runs-on: ubuntu-latest
    needs: [typecheck, format, lint, test]
    steps:
      - *checkout_step
      - *setup_step

      - name: Upload Chrome Extension
        uses: actions/upload-artifact@v7
        with:
          name: ChromeExtension
          path: '.output/chrome-mv3'
          if-no-files-found: error

      - name: Upload Firefox Extension
        uses: actions/upload-artifact@v7
        with:
          name: FirefoxExtension
          path: '.output/firefox-mv3'
          if-no-files-found: error
