name: Build and Test

on:
  pull_request:
    branches: [main]
    paths-ignore: ['**/*.md']
  push:
    branches: [main]
    paths-ignore: ['**/*.md']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck

      - name: Prettier
        run: npm run format

      - name: ESLint
        run: npm run lint

      - name: Build extensions
        run: |
          npm run build
          npm run build:firefox

      - name: Run AMO linter
        run: npx addons-linter .output/firefox-mv3

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ChromeExtension
          path: '.output/chrome-mv3'
          if-no-files-found: error

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: FirefoxExtension
          path: '.output/firefox-mv3'
          if-no-files-found: error
